# Generated by Django 3.1.6 on 2021-02-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210224_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_photo',
        ),
    ]
