# Generated by Django 3.1.6 on 2021-02-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20210224_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
