# Generated by Django 3.1.6 on 2021-02-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='grand_total',
            new_name='total',
        ),
    ]
