# Generated by Django 3.1.6 on 2021-02-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20210226_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tiers',
            options={'ordering': ['id']},
        ),
    ]
