# Generated by Django 3.1.6 on 2021-02-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20210226_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='snack_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='snack',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='snack',
            name='l_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
