# Generated by Django 3.1.6 on 2021-03-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_user_photo'),
        ('subscription', '0008_auto_20210227_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier', to='profiles.userprofile'),
        ),
    ]
