# Generated by Django 3.1.6 on 2021-03-09 23:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20210309_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='country',
            field=django_countries.fields.CountryField(default='Country', max_length=2),
        ),
        migrations.AlterField(
            model_name='snack',
            name='snack_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='stripe_pid',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
