# Generated by Django 3.1.6 on 2021-02-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['id']},
        ),
    ]
