# Generated by Django 3.1.6 on 2021-02-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20210215_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
