# Generated by Django 3.1.6 on 2021-02-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210224_1936'),
        ('photos', '0008_auto_20210221_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='owner',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='profiles.userprofile'),
        ),
    ]
