# Generated by Django 3.1.6 on 2021-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photospreview',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
