# Generated by Django 3.1.6 on 2021-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_photos', '0002_auto_20210303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photospreview',
            name='image',
            field=models.FileField(upload_to='preview'),
        ),
    ]
