# Generated by Django 3.1.6 on 2021-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preview_photos', '0003_auto_20210303_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='photospreview',
            name='image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
